databases:
  - name: ledgerx-db
    plan: free
    databaseName: ledgerx
    user: ledgerx
    postgresMajorVersion: 16

services:
  - type: web
    name: ledgerx-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ledgerx-db
          property: internalConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ledgerx-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ledgerx-db
          property: password
