databases:
  - name: ledgerx-db
    plan: free
    databaseName: ledgerx
    user: ledgerx
    postgresMajorVersion: 16

services:
  - type: web
    name: ledgerx-backend
    runtime: docker
    rootDir: LedgerX
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ledgerx-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ledgerx-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ledgerx-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ledgerx-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ledgerx-db
          property: password
